### ISSUE TITLE
Typo in components folder name

### ISSUE THREAD

**Issue by akdsco** [vivienneobrien/search-any-country#1]
The problem:

The folder `components` spelling is off. Please change

![viv-issue-one](https://user-images.githubusercontent.com/31314707/116100554-f3333980-a6a4-11eb-8fea-36bf5439108a.png)

Ideally, to start learning how to work with other developers using GitHub, you should follow below pattern:

- [x] - Create a new branch in your repository (a copy of your `master` branch)
- [x] - Fix the problem on that branch.
- [x] - Commit or keep on committing to that branch until the issue is sorted.
- [x] - Submit a PR (Pull Request) from your created branch to `master` branch.
- [x] - Someone (probably another dev in your team) checks (does code review) your proposal (think of Pull Request as a proposal to fix the issue)
- [x] - Someone else (probably your manager) merges Pull Request with `master` branch and therefore eventually accepts your code in or they can also close the PR, and your solution is not implemented.

Do you think you can do it?

Also, a good practice is to talk in here with people who create Issue, to find out details about the issue, especially if you don't really know what you should really fix. To do so, use below comment window, kind of works like a forum..

If at any stage of the above list you don't know-how, always best to google first, try, fail, try, fail and then start asking questions 😄 a pattern all good devs follow

**Comment by vivienneobrien** [comment]
Thanks Arkadiusz, no worries I do this all the time at work but have always pushed straight to master on my personal projects since I'm usually the only one working on them! I've just committed the spelling errors, thank you & good eye!

Heres my pull request:
<img width="400" alt="Screenshot 2021-04-26 at 18 18 17" src="https://user-images.githubusercontent.com/52012478/116124191-e53ce300-a6bb-11eb-8610-0631448f3d41.png">

Checking if can merge:
<img width="400" alt="Screenshot 2021-04-26 at 18 18 34" src="https://user-images.githubusercontent.com/52012478/116124196-e66e1000-a6bb-11eb-8413-db8bdd0d2c96.png">

Merge branch to master:
<img width="400" alt="Screenshot 2021-04-26 at 18 18 48" src="https://user-images.githubusercontent.com/52012478/116124201-e706a680-a6bb-11eb-84c5-273658527f58.png">
